from app.schemas import AmbientSignal, DemoScenario, GuestPersona, GuestProfile, PipelineRequest


DEMO_EMAIL = "asharma14@scu.edu"
DEMO_PHONES = ["+19255383461", "+19255778852"]


def demo_email(guest_name: str) -> str:
    return DEMO_EMAIL


def demo_phone(scenario_id: str) -> str:
    return DEMO_PHONES[sum(ord(character) for character in scenario_id) % len(DEMO_PHONES)]


def scenario(
    *,
    scenario_id: str,
    title: str,
    location: str,
    description: str,
    guest_name: str,
    suite: str,
    notes: str,
    nights: int,
    occasion: str | None,
    persona_segment: str,
    traits: list[str],
    preferences: dict[str, str],
    signals: list[tuple[str, str]],
) -> DemoScenario:
    return DemoScenario(
        id=scenario_id,
        title=title,
        description=f"{location} · {description}",
        request=PipelineRequest(
            profile=GuestProfile(
                guest_name=guest_name,
                suite=suite,
                property_location=location,
                email=demo_email(guest_name),
                phone=demo_phone(scenario_id),
                booking_notes=f"{location}: {notes}",
                arrival_date="2030-05-16",
                stay_nights=nights,
                occasion=occasion,
                persona=GuestPersona(
                    segment=persona_segment,
                    traits=traits,
                    preferences=preferences,
                ),
            ),
            ambient_signals=[
                AmbientSignal(time=time, signal=signal_text)
                for time, signal_text in signals
            ],
        ),
    )


DEMO_SCENARIOS = [
    DemoScenario(
        id="quiet-restoration",
        title="Quiet Restoration",
        description="Rosewood Menlo Park · A solo guest booked late and asked for a quiet weekend with very little friction.",
        request=PipelineRequest(
            profile=GuestProfile(
                guest_name="Avery Stone",
                suite="804",
                property_location="Rosewood Menlo Park",
                email=demo_email("Avery Stone"),
                phone=demo_phone("quiet-restoration"),
                booking_notes="Rosewood Menlo Park: quiet weekend, solo arrival, no calls if possible",
                arrival_date="2030-05-16",
                stay_nights=2,
                persona=GuestPersona(
                    segment="Restoration Seeker",
                    traits=["private", "overextended", "decision-light"],
                    preferences={
                        "pace": "unhurried",
                        "service_style": "quiet and opt-in",
                        "tone": "soft, precise, spacious",
                    },
                ),
            ),
            ambient_signals=[
                AmbientSignal(
                    time="05:47",
                    signal="Letter QR scanned early, then no further actions.",
                ),
                AmbientSignal(
                    time="11:18",
                    signal="Spa booking made after a quiet first morning.",
                ),
            ],
        ),
    ),
    DemoScenario(
        id="milestone-couple",
        title="Milestone Couple",
        description="Rosewood Hong Kong · A couple planned months ahead for their first trip together in two years.",
        request=PipelineRequest(
            profile=GuestProfile(
                guest_name="Mara and Julian Chen",
                suite="1203",
                property_location="Rosewood Hong Kong",
                email=demo_email("Mara and Julian Chen"),
                phone=demo_phone("milestone-couple"),
                booking_notes="Rosewood Hong Kong: first trip together in two years, private dinner preferred",
                arrival_date="2030-05-16",
                stay_nights=3,
                occasion="milestone",
                persona=GuestPersona(
                    segment="Milestone Couple",
                    traits=["ceremonial", "connected", "meaning-seeking"],
                    preferences={
                        "pace": "gentle build",
                        "service_style": "warm, prepared, quietly celebratory",
                        "tone": "ceremonial without sentimentality",
                    },
                ),
            ),
            ambient_signals=[
                AmbientSignal(
                    time="20:12",
                    signal="Private dining inquiry added before arrival.",
                ),
                AmbientSignal(
                    time="21:04",
                    signal="Guest asked concierge for a quiet place to mark the evening.",
                ),
            ],
        ),
    ),
    DemoScenario(
        id="celebration-discovery",
        title="Celebration / Discovery Guest",
        description="Rosewood New York · A bright, curious guest came to celebrate and wants the place to open up.",
        request=PipelineRequest(
            profile=GuestProfile(
                guest_name="Leila Hart",
                suite="617",
                property_location="Rosewood New York",
                email=demo_email("Leila Hart"),
                phone=demo_phone("celebration-discovery"),
                booking_notes="Rosewood New York: birthday weekend, loves food, design, hidden local places",
                arrival_date="2030-05-16",
                stay_nights=2,
                occasion="celebration",
                persona=GuestPersona(
                    segment="Celebration Explorer",
                    traits=["curious", "social", "taste-led"],
                    preferences={
                        "pace": "lively but edited",
                        "service_style": "confident, surprising, locally connected",
                        "tone": "bright, elegant, conspiratorial",
                    },
                ),
            ),
            ambient_signals=[
                AmbientSignal(
                    time="07:32",
                    signal="QR scanned after breakfast and chef note opened.",
                ),
                AmbientSignal(
                    time="09:15",
                    signal="Guest saved the gallery recommendation.",
                ),
            ],
        ),
    ),
]


DEMO_SCENARIOS.extend(
    [
        scenario(
            scenario_id="mayakoba-family-reset",
            title="Family Reset",
            location="Rosewood Mayakoba",
            description="Parents traveling with two children need ease, shade, and gentle discovery.",
            guest_name="Nadia and Samir Patel",
            suite="Lagoon 18",
            notes="family reset, children age six and nine, wants nature without logistics",
            nights=4,
            occasion="family",
            persona_segment="Family Restoration",
            traits=["protective", "warm", "logistics-averse"],
            preferences={"pace": "soft structure", "service_style": "anticipatory family care", "tone": "warm and capable"},
            signals=[("08:10", "Kids club inquiry opened before breakfast."), ("12:24", "Golf cart requested after lunch.")],
        ),
        scenario(
            scenario_id="hong-kong-dealmaker",
            title="Dealmaker Recovery",
            location="Rosewood Hong Kong",
            description="A finance executive has one night between negotiations and needs privacy.",
            guest_name="Elena Voronova",
            suite="Harbour 2602",
            notes="arriving after board dinner, early call, wants privacy and harbour view",
            nights=1,
            occasion="business",
            persona_segment="High-Control Executive",
            traits=["precise", "private", "time-constrained"],
            preferences={"pace": "compressed", "service_style": "exact and invisible", "tone": "crisp and calm"},
            signals=[("23:40", "Late arrival confirmed by airport transfer."), ("06:20", "In-room espresso requested before wake call.")],
        ),
        scenario(
            scenario_id="paris-couture-preview",
            title="Couture Preview",
            location="Rosewood Paris",
            description="A fashion editor is in Paris for fittings and wants beauty without spectacle.",
            guest_name="Ines Laurent",
            suite="Atelier 14",
            notes="couture fittings, private museum interest, avoids crowded restaurant rooms",
            nights=3,
            occasion="fashion week",
            persona_segment="Aesthetic Insider",
            traits=["observant", "taste-led", "crowd-avoidant"],
            preferences={"pace": "edited", "service_style": "quiet access", "tone": "elegant and knowing"},
            signals=[("18:05", "Guest saved the private gallery note."), ("22:11", "Requested late tea instead of bar reservation.")],
        ),
        scenario(
            scenario_id="london-literary-solo",
            title="Literary Solo Stay",
            location="Rosewood London",
            description="A novelist is alone in London finishing a manuscript.",
            guest_name="Thomas Vale",
            suite="Grosvenor 9",
            notes="solo writing week, prefers libraries, bookstores, quiet lunches",
            nights=5,
            occasion="creative retreat",
            persona_segment="Creative Solitude",
            traits=["reflective", "ritual-driven", "quietly curious"],
            preferences={"pace": "unhurried", "service_style": "discreet routine support", "tone": "literary and restrained"},
            signals=[("05:58", "QR scanned before sunrise."), ("15:42", "Do not disturb remained on through afternoon.")],
        ),
        scenario(
            scenario_id="bahamas-proposal",
            title="Proposal Weekend",
            location="Rosewood Nassau",
            description="One partner is planning a private proposal by the water.",
            guest_name="Mateo Rivera and Alex Kim",
            suite="Ocean 1107",
            notes="proposal planned, wants private beach moment, no public attention",
            nights=3,
            occasion="milestone",
            persona_segment="Private Ceremony",
            traits=["romantic", "nervous", "privacy-seeking"],
            preferences={"pace": "building toward sunset", "service_style": "warm but unseen", "tone": "tender and composed"},
            signals=[("10:02", "Concierge note added: ring handoff at 17:30."), ("19:18", "Private photographer held on standby.")],
        ),
        scenario(
            scenario_id="tuscany-wine-collector",
            title="Wine Collector",
            location="Rosewood Tuscany",
            description="A collector wants one rare bottle and a day shaped by the land.",
            guest_name="Arthur Okafor",
            suite="Villa Oliveto",
            notes="wine collector, Brunello interest, prefers private cellars and old vines",
            nights=4,
            occasion="collection",
            persona_segment="Collector Pilgrim",
            traits=["patient", "knowledgeable", "provenance-focused"],
            preferences={"pace": "slow reveal", "service_style": "expert access", "tone": "grounded and specific"},
            signals=[("09:44", "Cellar list opened twice."), ("16:08", "Guest declined group vineyard tour.")],
        ),
        scenario(
            scenario_id="santa-barbara-healing",
            title="Coastal Healing",
            location="Rosewood Montecito",
            description="A guest recovering from loss wants warmth, privacy, and ocean air.",
            guest_name="Clara Bennett",
            suite="Beach House 3",
            notes="quiet recovery trip, ocean walks, no celebration language",
            nights=3,
            occasion="recovery",
            persona_segment="Tender Recovery",
            traits=["grieving", "sensitive", "space-seeking"],
            preferences={"pace": "very gentle", "service_style": "held but not handled", "tone": "soft, safe, unsentimental"},
            signals=[("06:12", "Balcony breakfast requested without attendant entry."), ("13:30", "Spa garden bench reserved.")],
        ),
        scenario(
            scenario_id="new-york-gallery-couple",
            title="Gallery Couple",
            location="Rosewood New York",
            description="A couple is in New York for art, jazz, and a private anniversary dinner.",
            guest_name="Simone and David Rhee",
            suite="Madison 1508",
            notes="anniversary, gallery appointments, Bemelmans preferred, no tourist itinerary",
            nights=2,
            occasion="anniversary",
            persona_segment="Urban Cultural Couple",
            traits=["cultured", "romantic", "insider-oriented"],
            preferences={"pace": "city rhythm", "service_style": "classic and connected", "tone": "witty, warm, polished"},
            signals=[("17:22", "Gallery car confirmed."), ("21:45", "Jazz table requested through concierge.")],
        ),
        scenario(
            scenario_id="bermuda-golf-father-son",
            title="Father-Son Golf",
            location="Rosewood Bermuda",
            description="A father and adult son are reconnecting over golf after a long year.",
            guest_name="Hugh and Miles Carter",
            suite="Tucker 42",
            notes="father son golf trip, first travel together in years, wants easy conversation",
            nights=3,
            occasion="reconnection",
            persona_segment="Quiet Reconnection",
            traits=["reserved", "nostalgic", "outdoors-focused"],
            preferences={"pace": "morning energy", "service_style": "practical warmth", "tone": "plainspoken and kind"},
            signals=[("06:40", "Tee time checked twice."), ("14:05", "Lunch changed from club room to terrace.")],
        ),
        scenario(
            scenario_id="phuket-digital-detox",
            title="Digital Detox",
            location="Rosewood Phuket",
            description="A founder is trying to disappear from their phone for four days.",
            guest_name="Priya Malhotra",
            suite="Ocean Pool 22",
            notes="digital detox, no work calls, yoga, sea air, low decisions",
            nights=4,
            occasion="restoration",
            persona_segment="Burnout Founder",
            traits=["overstimulated", "disciplined", "privacy-seeking"],
            preferences={"pace": "decelerating", "service_style": "quiet containment", "tone": "minimal and grounding"},
            signals=[("05:30", "Phone locker request added."), ("11:05", "Yoga mat delivered but class not booked.")],
        ),
        scenario(
            scenario_id="vienna-music-patron",
            title="Music Patron",
            location="Rosewood Vienna",
            description="A patron is visiting for chamber music and old-world ritual.",
            guest_name="Beatrice Stein",
            suite="Hofburg 6",
            notes="chamber music, private salon, prefers historic detail and formal service",
            nights=2,
            occasion="culture",
            persona_segment="Old-World Patron",
            traits=["formal", "historically minded", "ritual-loving"],
            preferences={"pace": "ceremonial", "service_style": "polished and precise", "tone": "graceful and cultured"},
            signals=[("16:00", "Opera cloakroom note opened."), ("22:36", "Nightcap requested in suite.")],
        ),
        scenario(
            scenario_id="doha-family-celebration",
            title="Family Celebration",
            location="Rosewood Doha",
            description="Three generations are gathering for a private birthday dinner.",
            guest_name="The Al-Mansour Family",
            suite="Pearl Residence",
            notes="three generation birthday, privacy, child-friendly details, family dinner",
            nights=2,
            occasion="celebration",
            persona_segment="Multigenerational Celebration",
            traits=["family-centered", "ceremonial", "detail-aware"],
            preferences={"pace": "coordinated", "service_style": "generous and private", "tone": "warm and dignified"},
            signals=[("09:12", "Children's breakfast preferences updated."), ("18:25", "Private dining room confirmed.")],
        ),
        scenario(
            scenario_id="munich-design-founder",
            title="Design Founder",
            location="Rosewood Munich",
            description="A design founder wants architecture, craft, and one precise dinner.",
            guest_name="Jonas Weber",
            suite="Maximilian 31",
            notes="design founder, architecture walk, craft studios, one excellent dinner",
            nights=2,
            occasion="discovery",
            persona_segment="Design-Led Explorer",
            traits=["visual", "efficient", "craft-focused"],
            preferences={"pace": "clean and edited", "service_style": "expert local access", "tone": "sharp, modern, specific"},
            signals=[("08:48", "Architecture route opened."), ("13:15", "Guest saved furniture atelier note.")],
        ),
        scenario(
            scenario_id="kauai-honeymoon-stillness",
            title="Honeymoon Stillness",
            location="Rosewood Kona",
            description="Newlyweds want the honeymoon to feel unplanned and protected.",
            guest_name="Amara and Theo Brooks",
            suite="Hale 12",
            notes="honeymoon, wants privacy, ocean, no packed itinerary",
            nights=5,
            occasion="milestone",
            persona_segment="Newlywed Stillness",
            traits=["tender", "private", "nature-seeking"],
            preferences={"pace": "slow and intimate", "service_style": "protective invisibility", "tone": "warm, spare, luminous"},
            signals=[("07:05", "Breakfast moved to lanai."), ("19:00", "Sunset canoe note opened.")],
        ),
        scenario(
            scenario_id="san-miguel-artist-return",
            title="Artist Return",
            location="Rosewood San Miguel de Allende",
            description="A painter returns after years and wants color, memory, and quiet studios.",
            guest_name="Lucia Herrera",
            suite="Cielo 5",
            notes="artist returning after ten years, wants pigment shops, courtyards, old friends",
            nights=4,
            occasion="return",
            persona_segment="Returning Artist",
            traits=["nostalgic", "sensory", "quietly social"],
            preferences={"pace": "wandering", "service_style": "local memory and introductions", "tone": "colorful but restrained"},
            signals=[("10:30", "Guest asked about old pigment supplier."), ("17:44", "Rooftop dinner declined for courtyard table.")],
        ),
        scenario(
            scenario_id="madrid-football-father",
            title="Football Weekend",
            location="Rosewood Madrid",
            description="A father is taking his daughter to her first major football match.",
            guest_name="Diego and Sofia Alvarez",
            suite="Castellana 808",
            notes="daughter first football match, wants excitement but not chaos",
            nights=2,
            occasion="family milestone",
            persona_segment="Shared First",
            traits=["excited", "protective", "memory-making"],
            preferences={"pace": "bright and managed", "service_style": "energetic but controlled", "tone": "warm, vivid, practical"},
            signals=[("08:20", "Stadium transfer confirmed."), ("21:10", "Dessert note saved for daughter.")],
        ),
        scenario(
            scenario_id="washington-diplomat",
            title="Diplomatic Quiet",
            location="Rosewood Washington DC",
            description="A diplomat needs discretion before a public morning engagement.",
            guest_name="Ambassador Laila Haddad",
            suite="Canal 701",
            notes="public engagement tomorrow, discretion, private breakfast, no names in common areas",
            nights=1,
            occasion="official visit",
            persona_segment="Public Figure Privacy",
            traits=["discreet", "schedule-bound", "security-aware"],
            preferences={"pace": "exact", "service_style": "formal discretion", "tone": "measured and respectful"},
            signals=[("22:00", "Security elevator hold added."), ("06:00", "Private breakfast set before motorcade.")],
        ),
        scenario(
            scenario_id="amsterdam-culinary-sisters",
            title="Culinary Sisters",
            location="Rosewood Amsterdam",
            description="Two sisters are traveling for markets, canals, design shops, and a birthday.",
            guest_name="Mina and Celine Duarte",
            suite="Canal 22",
            notes="sisters birthday trip, food markets, canal walk, vintage jewelry",
            nights=3,
            occasion="celebration",
            persona_segment="Culinary Kinship",
            traits=["playful", "food-led", "sentimental"],
            preferences={"pace": "lively and warm", "service_style": "generous local introductions", "tone": "bright, familial, delicious"},
            signals=[("09:40", "Market route opened."), ("15:12", "Vintage jewelry note saved.")],
        ),
        scenario(
            scenario_id="miyakojima-architecture-pilgrim",
            title="Architecture Pilgrim",
            location="Rosewood Miyakojima",
            description="An architect wants silence, island materials, and one impossible-to-find pottery studio.",
            guest_name="Kenji Nakamura",
            suite="Villa 17",
            notes="architecture research, island craft, quiet materials, no shopping lists",
            nights=4,
            occasion="research",
            persona_segment="Material Pilgrim",
            traits=["precise", "minimal", "deeply observant"],
            preferences={"pace": "focused", "service_style": "quiet expertise", "tone": "spare and exact"},
            signals=[("06:45", "Garden map opened."), ("20:30", "Guest declined nightlife suggestions.")],
        ),
        scenario(
            scenario_id="vancouver-wellness-mother",
            title="Wellness Mother",
            location="Rosewood Vancouver",
            description="A mother traveling alone wants sleep, spa, and one beautiful bookstore.",
            guest_name="Mei Anderson",
            suite="Georgia 904",
            notes="solo mother reset, sleep, spa, bookstore, no pressure",
            nights=2,
            occasion="restoration",
            persona_segment="Caregiver Reset",
            traits=["tired", "gentle", "bookish"],
            preferences={"pace": "rest-first", "service_style": "nurturing but hands-off", "tone": "soft and permission-giving"},
            signals=[("10:18", "Late checkout requested."), ("12:05", "Spa menu opened, no booking yet.")],
        ),
        scenario(
            scenario_id="menlo-park-founder-offsite",
            title="Founder Offsite",
            location="Rosewood Menlo Park",
            description="A startup founder needs one clear day before a board offsite.",
            guest_name="Evan Pierce",
            suite="Garden 612",
            notes="board offsite, founder needs quiet prep, no networking suggestions",
            nights=2,
            occasion="business",
            persona_segment="Focused Founder",
            traits=["compressed", "strategic", "low-noise"],
            preferences={"pace": "precise and protected", "service_style": "quiet executive support", "tone": "clear, minimal, grounded"},
            signals=[("06:05", "Conference room note opened."), ("21:18", "Requested herbal tea and printer access.")],
        ),
        scenario(
            scenario_id="menlo-park-ai-summit-speaker",
            title="AI Summit Speaker",
            location="Rosewood Menlo Park",
            description="A keynote speaker is attending a Stanford-adjacent AI summit and needs preparation, calm, and a clean return.",
            guest_name="Dr. Naomi Iyer",
            suite="Oak 811",
            notes="AI summit keynote, quiet prep, pressed suit, transfer to campus, no networking dinner",
            nights=2,
            occasion="conference",
            persona_segment="Conference Speaker",
            traits=["public-facing", "precise", "energy-protective"],
            preferences={"pace": "prepared and buffered", "service_style": "exact, quiet, event-aware", "tone": "composed and useful"},
            signals=[("06:30", "Presentation deck opened from QR."), ("21:10", "Guest requested garment pressing and early breakfast.")],
        ),
        scenario(
            scenario_id="hong-kong-finance-conference",
            title="Finance Conference",
            location="Rosewood Hong Kong",
            description="An executive is attending a finance conference and needs privacy between sessions.",
            guest_name="Caleb Wong",
            suite="Harbour 2108",
            notes="finance conference, back-to-back panels, harbor-view calls, private dinner, no crowded bar",
            nights=3,
            occasion="conference",
            persona_segment="Conference Executive",
            traits=["time-bound", "private", "high-control"],
            preferences={"pace": "efficient and restorative", "service_style": "invisible executive support", "tone": "crisp, calm, polished"},
            signals=[("05:55", "In-room espresso requested before first panel."), ("18:05", "Guest declined networking reception.")],
        ),
        scenario(
            scenario_id="new-york-climate-panelist",
            title="Climate Forum Panelist",
            location="Rosewood New York",
            description="A policy leader is in town for a climate forum and wants one thoughtful decompression plan afterward.",
            guest_name="Mara Okonkwo",
            suite="Madison 1904",
            notes="climate forum panel, public event, car timing, light lunch, post-panel quiet dinner",
            nights=2,
            occasion="event",
            persona_segment="Public Panelist",
            traits=["mission-driven", "scheduled", "conversation-heavy"],
            preferences={"pace": "structured with decompression", "service_style": "timely and discreet", "tone": "intelligent, calm, grounded"},
            signals=[("07:45", "Panel agenda opened."), ("16:20", "Guest skipped cocktail reception suggestion.")],
        ),
        scenario(
            scenario_id="london-medical-congress",
            title="Medical Congress",
            location="Rosewood London",
            description="A surgeon is attending a medical congress and wants quiet meals, walking time, and no social pressure.",
            guest_name="Dr. Eva Markham",
            suite="Holborn 1206",
            notes="medical congress, early sessions, quiet dinner, restorative walk, no late events",
            nights=3,
            occasion="conference",
            persona_segment="Scientific Delegate",
            traits=["focused", "fatigued", "quietly curious"],
            preferences={"pace": "clinical precision with softness", "service_style": "quiet readiness", "tone": "clear, gentle, intelligent"},
            signals=[("06:05", "Congress schedule opened."), ("20:15", "Room service requested instead of restaurant booking.")],
        ),
        scenario(
            scenario_id="washington-board-meeting",
            title="Board Meeting",
            location="Rosewood Washington DC",
            description="A board chair has a private morning meeting and wants discretion, timing, and a composed evening.",
            guest_name="Marisol Grant",
            suite="Canal 804",
            notes="board meeting, private breakfast, secure car timing, no lobby greeting, quiet dinner",
            nights=1,
            occasion="business meeting",
            persona_segment="Board Chair",
            traits=["discreet", "schedule-bound", "high-trust"],
            preferences={"pace": "exact and buffered", "service_style": "formal discretion", "tone": "measured and composed"},
            signals=[("06:15", "Board packet opened."), ("19:05", "Guest declined reception invitation.")],
        ),
        scenario(
            scenario_id="menlo-park-stanford-parents",
            title="Stanford Parents",
            location="Rosewood Menlo Park",
            description="Parents are visiting their daughter after her first difficult quarter.",
            guest_name="Anika and Paul Mercer",
            suite="Courtyard 418",
            notes="Stanford family visit, daughter overwhelmed, wants comfort and low-pressure dinner",
            nights=3,
            occasion="family",
            persona_segment="Gentle Family Anchor",
            traits=["protective", "warm", "emotionally careful"],
            preferences={"pace": "softly structured", "service_style": "family-aware and unobtrusive", "tone": "reassuring and humane"},
            signals=[("09:22", "Casual dinner options opened."), ("16:40", "Guest asked for a quiet table, not a scene.")],
        ),
        scenario(
            scenario_id="menlo-park-venture-couple",
            title="Venture Couple",
            location="Rosewood Menlo Park",
            description="A couple both in tech wants to reconnect without talking about work.",
            guest_name="Riya Shah and Daniel Kim",
            suite="Oak 704",
            notes="couple in tech, no work talk, wants bike ride, dinner, quiet reconnection",
            nights=2,
            occasion="milestone",
            persona_segment="Work-Weary Couple",
            traits=["ambitious", "overextended", "reconnecting"],
            preferences={"pace": "unplugged and warm", "service_style": "protect from decisions", "tone": "warm, lightly ceremonial"},
            signals=[("07:10", "Bike route opened."), ("19:05", "Phones placed in suite safe by request.")],
        ),
        scenario(
            scenario_id="menlo-park-alumni-return",
            title="Alumni Return",
            location="Rosewood Menlo Park",
            description="A Stanford alum returns for the first time in twenty years.",
            guest_name="Marcus Ellison",
            suite="Arboretum 509",
            notes="Stanford alumni return, nostalgic but private, wants campus-adjacent memory not crowds",
            nights=2,
            occasion="return",
            persona_segment="Private Nostalgic",
            traits=["reflective", "reserved", "memory-led"],
            preferences={"pace": "slow recall", "service_style": "quiet local memory", "tone": "restrained, specific, kind"},
            signals=[("06:50", "Campus walk note opened."), ("12:44", "Guest skipped alumni reception recommendation.")],
        ),
        scenario(
            scenario_id="menlo-park-wellness-investor",
            title="Wellness Investor",
            location="Rosewood Menlo Park",
            description="An investor is between meetings and wants sleep, movement, and clean food.",
            guest_name="Sofia Tan",
            suite="Terrace 331",
            notes="investor meetings, wellness priority, sleep, trainer, clean dinner",
            nights=1,
            occasion="business restoration",
            persona_segment="High-Functioning Restorer",
            traits=["disciplined", "health-focused", "time-boxed"],
            preferences={"pace": "efficient recovery", "service_style": "wellness-forward and exact", "tone": "calm, capable, direct"},
            signals=[("05:45", "Trainer request confirmed."), ("20:30", "Asked for dinner without alcohol pairing.")],
        ),
        scenario(
            scenario_id="menlo-park-art-collector",
            title="Art Collector",
            location="Rosewood Menlo Park",
            description="A collector wants Bay Area craft, private access, and no gallery crowds.",
            guest_name="Helena Sato",
            suite="Gallery 219",
            notes="art collector, Bay Area craft, private studio access, no crowded openings",
            nights=3,
            occasion="discovery",
            persona_segment="Quiet Collector",
            traits=["observant", "provenance-focused", "private"],
            preferences={"pace": "edited and slow", "service_style": "discreet introductions", "tone": "precise, visual, understated"},
            signals=[("10:05", "Studio visit note saved."), ("15:36", "Guest declined public gallery reception.")],
        ),
    ]
)
