from app.schemas import AmbientSignal, DemoScenario, GuestPersona, GuestProfile, PipelineRequest


def scenario(
    *,
    scenario_id: str,
    title: str,
    location: str,
    description: str,
    guest_name: str,
    suite: str,
    notes: str,
    nights: int,
    occasion: str | None,
    persona_segment: str,
    traits: list[str],
    preferences: dict[str, str],
    signals: list[tuple[str, str]],
) -> DemoScenario:
    return DemoScenario(
        id=scenario_id,
        title=title,
        description=f"{location} · {description}",
        request=PipelineRequest(
            profile=GuestProfile(
                guest_name=guest_name,
                suite=suite,
                booking_notes=f"{location}: {notes}",
                arrival_date="2030-05-16",
                stay_nights=nights,
                occasion=occasion,
                persona=GuestPersona(
                    segment=persona_segment,
                    traits=traits,
                    preferences=preferences,
                ),
            ),
            ambient_signals=[
                AmbientSignal(time=time, signal=signal_text)
                for time, signal_text in signals
            ],
        ),
    )


DEMO_SCENARIOS = [
    DemoScenario(
        id="quiet-restoration",
        title="Quiet Restoration",
        description="A solo guest booked late and asked for a quiet weekend with very little friction.",
        request=PipelineRequest(
            profile=GuestProfile(
                guest_name="Avery Stone",
                suite="804",
                booking_notes="quiet weekend, solo arrival, no calls if possible",
                arrival_date="2030-05-16",
                stay_nights=2,
                persona=GuestPersona(
                    segment="Restoration Seeker",
                    traits=["private", "overextended", "decision-light"],
                    preferences={
                        "pace": "unhurried",
                        "service_style": "quiet and opt-in",
                        "tone": "soft, precise, spacious",
                    },
                ),
            ),
            ambient_signals=[
                AmbientSignal(
                    time="05:47",
                    signal="Letter QR scanned early, then no further actions.",
                ),
                AmbientSignal(
                    time="11:18",
                    signal="Spa booking made after a quiet first morning.",
                ),
            ],
        ),
    ),
    DemoScenario(
        id="milestone-couple",
        title="Milestone Couple",
        description="A couple planned months ahead for their first trip together in two years.",
        request=PipelineRequest(
            profile=GuestProfile(
                guest_name="Mara and Julian Chen",
                suite="1203",
                booking_notes="first trip together in two years, private dinner preferred",
                arrival_date="2030-05-16",
                stay_nights=3,
                occasion="milestone",
                persona=GuestPersona(
                    segment="Milestone Couple",
                    traits=["ceremonial", "connected", "meaning-seeking"],
                    preferences={
                        "pace": "gentle build",
                        "service_style": "warm, prepared, quietly celebratory",
                        "tone": "ceremonial without sentimentality",
                    },
                ),
            ),
            ambient_signals=[
                AmbientSignal(
                    time="20:12",
                    signal="Private dining inquiry added before arrival.",
                ),
                AmbientSignal(
                    time="21:04",
                    signal="Guest asked concierge for a quiet place to mark the evening.",
                ),
            ],
        ),
    ),
    DemoScenario(
        id="celebration-discovery",
        title="Celebration / Discovery Guest",
        description="A bright, curious guest came to celebrate and wants the place to open up.",
        request=PipelineRequest(
            profile=GuestProfile(
                guest_name="Leila Hart",
                suite="617",
                booking_notes="birthday weekend, loves food, design, hidden local places",
                arrival_date="2030-05-16",
                stay_nights=2,
                occasion="celebration",
                persona=GuestPersona(
                    segment="Celebration Explorer",
                    traits=["curious", "social", "taste-led"],
                    preferences={
                        "pace": "lively but edited",
                        "service_style": "confident, surprising, locally connected",
                        "tone": "bright, elegant, conspiratorial",
                    },
                ),
            ),
            ambient_signals=[
                AmbientSignal(
                    time="07:32",
                    signal="QR scanned after breakfast and chef note opened.",
                ),
                AmbientSignal(
                    time="09:15",
                    signal="Guest saved the gallery recommendation.",
                ),
            ],
        ),
    ),
]


DEMO_SCENARIOS.extend(
    [
        scenario(
            scenario_id="mayakoba-family-reset",
            title="Family Reset",
            location="Rosewood Mayakoba",
            description="Parents traveling with two children need ease, shade, and gentle discovery.",
            guest_name="Nadia and Samir Patel",
            suite="Lagoon 18",
            notes="family reset, children age six and nine, wants nature without logistics",
            nights=4,
            occasion="family",
            persona_segment="Family Restoration",
            traits=["protective", "warm", "logistics-averse"],
            preferences={"pace": "soft structure", "service_style": "anticipatory family care", "tone": "warm and capable"},
            signals=[("08:10", "Kids club inquiry opened before breakfast."), ("12:24", "Golf cart requested after lunch.")],
        ),
        scenario(
            scenario_id="hong-kong-dealmaker",
            title="Dealmaker Recovery",
            location="Rosewood Hong Kong",
            description="A finance executive has one night between negotiations and needs privacy.",
            guest_name="Elena Voronova",
            suite="Harbour 2602",
            notes="arriving after board dinner, early call, wants privacy and harbour view",
            nights=1,
            occasion="business",
            persona_segment="High-Control Executive",
            traits=["precise", "private", "time-constrained"],
            preferences={"pace": "compressed", "service_style": "exact and invisible", "tone": "crisp and calm"},
            signals=[("23:40", "Late arrival confirmed by airport transfer."), ("06:20", "In-room espresso requested before wake call.")],
        ),
        scenario(
            scenario_id="paris-couture-preview",
            title="Couture Preview",
            location="Hotel de Crillon, A Rosewood Hotel",
            description="A fashion editor is in Paris for fittings and wants beauty without spectacle.",
            guest_name="Ines Laurent",
            suite="Atelier 14",
            notes="couture fittings, private museum interest, avoids crowded restaurant rooms",
            nights=3,
            occasion="fashion week",
            persona_segment="Aesthetic Insider",
            traits=["observant", "taste-led", "crowd-avoidant"],
            preferences={"pace": "edited", "service_style": "quiet access", "tone": "elegant and knowing"},
            signals=[("18:05", "Guest saved the private gallery note."), ("22:11", "Requested late tea instead of bar reservation.")],
        ),
        scenario(
            scenario_id="london-literary-solo",
            title="Literary Solo Stay",
            location="The Chancery Rosewood",
            description="A novelist is alone in London finishing a manuscript.",
            guest_name="Thomas Vale",
            suite="Grosvenor 9",
            notes="solo writing week, prefers libraries, bookstores, quiet lunches",
            nights=5,
            occasion="creative retreat",
            persona_segment="Creative Solitude",
            traits=["reflective", "ritual-driven", "quietly curious"],
            preferences={"pace": "unhurried", "service_style": "discreet routine support", "tone": "literary and restrained"},
            signals=[("05:58", "QR scanned before sunrise."), ("15:42", "Do not disturb remained on through afternoon.")],
        ),
        scenario(
            scenario_id="bahamas-proposal",
            title="Proposal Weekend",
            location="Rosewood Baha Mar",
            description="One partner is planning a private proposal by the water.",
            guest_name="Mateo Rivera and Alex Kim",
            suite="Ocean 1107",
            notes="proposal planned, wants private beach moment, no public attention",
            nights=3,
            occasion="milestone",
            persona_segment="Private Ceremony",
            traits=["romantic", "nervous", "privacy-seeking"],
            preferences={"pace": "building toward sunset", "service_style": "warm but unseen", "tone": "tender and composed"},
            signals=[("10:02", "Concierge note added: ring handoff at 17:30."), ("19:18", "Private photographer held on standby.")],
        ),
        scenario(
            scenario_id="tuscany-wine-collector",
            title="Wine Collector",
            location="Rosewood Castiglion del Bosco",
            description="A collector wants one rare bottle and a day shaped by the land.",
            guest_name="Arthur Okafor",
            suite="Villa Oliveto",
            notes="wine collector, Brunello interest, prefers private cellars and old vines",
            nights=4,
            occasion="collection",
            persona_segment="Collector Pilgrim",
            traits=["patient", "knowledgeable", "provenance-focused"],
            preferences={"pace": "slow reveal", "service_style": "expert access", "tone": "grounded and specific"},
            signals=[("09:44", "Cellar list opened twice."), ("16:08", "Guest declined group vineyard tour.")],
        ),
        scenario(
            scenario_id="santa-barbara-healing",
            title="Coastal Healing",
            location="Rosewood Miramar Beach",
            description="A guest recovering from loss wants warmth, privacy, and ocean air.",
            guest_name="Clara Bennett",
            suite="Beach House 3",
            notes="quiet recovery trip, ocean walks, no celebration language",
            nights=3,
            occasion="recovery",
            persona_segment="Tender Recovery",
            traits=["grieving", "sensitive", "space-seeking"],
            preferences={"pace": "very gentle", "service_style": "held but not handled", "tone": "soft, safe, unsentimental"},
            signals=[("06:12", "Balcony breakfast requested without attendant entry."), ("13:30", "Spa garden bench reserved.")],
        ),
        scenario(
            scenario_id="new-york-gallery-couple",
            title="Gallery Couple",
            location="The Carlyle, A Rosewood Hotel",
            description="A couple is in New York for art, jazz, and a private anniversary dinner.",
            guest_name="Simone and David Rhee",
            suite="Madison 1508",
            notes="anniversary, gallery appointments, Bemelmans preferred, no tourist itinerary",
            nights=2,
            occasion="anniversary",
            persona_segment="Urban Cultural Couple",
            traits=["cultured", "romantic", "insider-oriented"],
            preferences={"pace": "city rhythm", "service_style": "classic and connected", "tone": "witty, warm, polished"},
            signals=[("17:22", "Gallery car confirmed."), ("21:45", "Jazz table requested through concierge.")],
        ),
        scenario(
            scenario_id="bermuda-golf-father-son",
            title="Father-Son Golf",
            location="Rosewood Bermuda",
            description="A father and adult son are reconnecting over golf after a long year.",
            guest_name="Hugh and Miles Carter",
            suite="Tucker 42",
            notes="father son golf trip, first travel together in years, wants easy conversation",
            nights=3,
            occasion="reconnection",
            persona_segment="Quiet Reconnection",
            traits=["reserved", "nostalgic", "outdoors-focused"],
            preferences={"pace": "morning energy", "service_style": "practical warmth", "tone": "plainspoken and kind"},
            signals=[("06:40", "Tee time checked twice."), ("14:05", "Lunch changed from club room to terrace.")],
        ),
        scenario(
            scenario_id="phuket-digital-detox",
            title="Digital Detox",
            location="Rosewood Phuket",
            description="A founder is trying to disappear from their phone for four days.",
            guest_name="Priya Malhotra",
            suite="Ocean Pool 22",
            notes="digital detox, no work calls, yoga, sea air, low decisions",
            nights=4,
            occasion="restoration",
            persona_segment="Burnout Founder",
            traits=["overstimulated", "disciplined", "privacy-seeking"],
            preferences={"pace": "decelerating", "service_style": "quiet containment", "tone": "minimal and grounding"},
            signals=[("05:30", "Phone locker request added."), ("11:05", "Yoga mat delivered but class not booked.")],
        ),
        scenario(
            scenario_id="vienna-music-patron",
            title="Music Patron",
            location="Rosewood Vienna",
            description="A patron is visiting for chamber music and old-world ritual.",
            guest_name="Beatrice Stein",
            suite="Hofburg 6",
            notes="chamber music, private salon, prefers historic detail and formal service",
            nights=2,
            occasion="culture",
            persona_segment="Old-World Patron",
            traits=["formal", "historically minded", "ritual-loving"],
            preferences={"pace": "ceremonial", "service_style": "polished and precise", "tone": "graceful and cultured"},
            signals=[("16:00", "Opera cloakroom note opened."), ("22:36", "Nightcap requested in suite.")],
        ),
        scenario(
            scenario_id="doha-family-celebration",
            title="Family Celebration",
            location="Rosewood Doha",
            description="Three generations are gathering for a private birthday dinner.",
            guest_name="The Al-Mansour Family",
            suite="Pearl Residence",
            notes="three generation birthday, privacy, child-friendly details, family dinner",
            nights=2,
            occasion="celebration",
            persona_segment="Multigenerational Celebration",
            traits=["family-centered", "ceremonial", "detail-aware"],
            preferences={"pace": "coordinated", "service_style": "generous and private", "tone": "warm and dignified"},
            signals=[("09:12", "Children's breakfast preferences updated."), ("18:25", "Private dining room confirmed.")],
        ),
        scenario(
            scenario_id="munich-design-founder",
            title="Design Founder",
            location="Rosewood Munich",
            description="A design founder wants architecture, craft, and one precise dinner.",
            guest_name="Jonas Weber",
            suite="Maximilian 31",
            notes="design founder, architecture walk, craft studios, one excellent dinner",
            nights=2,
            occasion="discovery",
            persona_segment="Design-Led Explorer",
            traits=["visual", "efficient", "craft-focused"],
            preferences={"pace": "clean and edited", "service_style": "expert local access", "tone": "sharp, modern, specific"},
            signals=[("08:48", "Architecture route opened."), ("13:15", "Guest saved furniture atelier note.")],
        ),
        scenario(
            scenario_id="kauai-honeymoon-stillness",
            title="Honeymoon Stillness",
            location="Kona Village, A Rosewood Resort",
            description="Newlyweds want the honeymoon to feel unplanned and protected.",
            guest_name="Amara and Theo Brooks",
            suite="Hale 12",
            notes="honeymoon, wants privacy, ocean, no packed itinerary",
            nights=5,
            occasion="milestone",
            persona_segment="Newlywed Stillness",
            traits=["tender", "private", "nature-seeking"],
            preferences={"pace": "slow and intimate", "service_style": "protective invisibility", "tone": "warm, spare, luminous"},
            signals=[("07:05", "Breakfast moved to lanai."), ("19:00", "Sunset canoe note opened.")],
        ),
        scenario(
            scenario_id="san-miguel-artist-return",
            title="Artist Return",
            location="Rosewood San Miguel de Allende",
            description="A painter returns after years and wants color, memory, and quiet studios.",
            guest_name="Lucia Herrera",
            suite="Cielo 5",
            notes="artist returning after ten years, wants pigment shops, courtyards, old friends",
            nights=4,
            occasion="return",
            persona_segment="Returning Artist",
            traits=["nostalgic", "sensory", "quietly social"],
            preferences={"pace": "wandering", "service_style": "local memory and introductions", "tone": "colorful but restrained"},
            signals=[("10:30", "Guest asked about old pigment supplier."), ("17:44", "Rooftop dinner declined for courtyard table.")],
        ),
        scenario(
            scenario_id="madrid-football-father",
            title="Football Weekend",
            location="Rosewood Villa Magna",
            description="A father is taking his daughter to her first major football match.",
            guest_name="Diego and Sofia Alvarez",
            suite="Castellana 808",
            notes="daughter first football match, wants excitement but not chaos",
            nights=2,
            occasion="family milestone",
            persona_segment="Shared First",
            traits=["excited", "protective", "memory-making"],
            preferences={"pace": "bright and managed", "service_style": "energetic but controlled", "tone": "warm, vivid, practical"},
            signals=[("08:20", "Stadium transfer confirmed."), ("21:10", "Dessert note saved for daughter.")],
        ),
        scenario(
            scenario_id="washington-diplomat",
            title="Diplomatic Quiet",
            location="Rosewood Washington, D.C.",
            description="A diplomat needs discretion before a public morning engagement.",
            guest_name="Ambassador Laila Haddad",
            suite="Canal 701",
            notes="public engagement tomorrow, discretion, private breakfast, no names in common areas",
            nights=1,
            occasion="official visit",
            persona_segment="Public Figure Privacy",
            traits=["discreet", "schedule-bound", "security-aware"],
            preferences={"pace": "exact", "service_style": "formal discretion", "tone": "measured and respectful"},
            signals=[("22:00", "Security elevator hold added."), ("06:00", "Private breakfast set before motorcade.")],
        ),
        scenario(
            scenario_id="rome-culinary-sisters",
            title="Culinary Sisters",
            location="Rosewood Rome",
            description="Two sisters are traveling for markets, pasta, and a birthday.",
            guest_name="Mina and Celine Duarte",
            suite="Palazzo 22",
            notes="sisters birthday trip, food markets, pasta class, vintage jewelry",
            nights=3,
            occasion="celebration",
            persona_segment="Culinary Kinship",
            traits=["playful", "food-led", "sentimental"],
            preferences={"pace": "lively and warm", "service_style": "generous local introductions", "tone": "bright, familial, delicious"},
            signals=[("09:40", "Market route opened."), ("15:12", "Vintage jewelry note saved.")],
        ),
        scenario(
            scenario_id="tokyo-architecture-pilgrim",
            title="Architecture Pilgrim",
            location="Rosewood Tokyo",
            description="An architect wants silence, precision, and one impossible-to-find tea room.",
            guest_name="Kenji Nakamura",
            suite="Aoyama 1704",
            notes="architecture research, tea rooms, quiet materials, no shopping lists",
            nights=4,
            occasion="research",
            persona_segment="Material Pilgrim",
            traits=["precise", "minimal", "deeply observant"],
            preferences={"pace": "focused", "service_style": "quiet expertise", "tone": "spare and exact"},
            signals=[("06:45", "Garden map opened."), ("20:30", "Guest declined nightlife suggestions.")],
        ),
        scenario(
            scenario_id="vancouver-wellness-mother",
            title="Wellness Mother",
            location="Rosewood Hotel Georgia",
            description="A mother traveling alone wants sleep, spa, and one beautiful bookstore.",
            guest_name="Mei Anderson",
            suite="Georgia 904",
            notes="solo mother reset, sleep, spa, bookstore, no pressure",
            nights=2,
            occasion="restoration",
            persona_segment="Caregiver Reset",
            traits=["tired", "gentle", "bookish"],
            preferences={"pace": "rest-first", "service_style": "nurturing but hands-off", "tone": "soft and permission-giving"},
            signals=[("10:18", "Late checkout requested."), ("12:05", "Spa menu opened, no booking yet.")],
        ),
    ]
)
